python:
  - changed-files:
      - any-glob-to-any-file: 'backend/**'

frontend:
  - changed-files:
      - any-glob-to-any-file: 'frontend/**'

typescript:
  - changed-files:
      - any-glob-to-any-file: ['frontend/**/*.ts', 'frontend/**/*.tsx']

javascript:
  - changed-files:
      - any-glob-to-any-file: 'frontend/**/*.{js,jsx,mjs,cjs}'

docker:
  - changed-files:
      - any-glob-to-any-file: ['**/Dockerfile*', 'docker-compose*.yml']

github_actions:
  - changed-files:
      - any-glob-to-any-file: '.github/workflows/**'
