DEFAULT_OCCASION = "casual"
DEFAULT_TEMPERATURE_UNIT = "celsius"
DEFAULT_TEMPERATURE_SENSITIVITY = "normal"
DEFAULT_LAYERING_PREFERENCE = "moderate"
DEFAULT_VARIETY_LEVEL = "moderate"
DEFAULT_PREFER_UNDERUSED_ITEMS = True
